openapi: "3.0.0"
info:
  version: 1.0.0
  title: File Converter

paths:
  /api/v1/{inputFormat}/{outputFormat}/:
    get:
      summary: Convert a file from one format to another
      parameters:
        - in: path
          name: inputFormat
          schema:
            type: integer
          required: true
          description: index+1 of input file format from internal file formats list
        - in: path
          name: outputFormat
          schema:
            type: integer
          required: true
          description: index+1 of output file format from internal file formats list
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                  format: binary
                inputLineSeparator:
                  type: string
                inputElementSeparator:
                  type: string
                outputLineSeparator:
                  type: string
                outputElementSeparator:
                  type: string
      responses:
        '200':
          description: Converted output in desired format
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
